# Generated by Django 6.0.3 on 2026-03-21 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_add_cover_url_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField()),
                ('start_position', models.JSONField(default=dict)),
                ('end_position', models.JSONField(default=dict)),
                ('selected_text', models.TextField()),
                ('color', models.CharField(default='#ffff00', max_length=7)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='books.book')),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField()),
                ('position', models.JSONField(default=dict)),
                ('content', models.TextField()),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='books.book')),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pages_read', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('screenshot_attempts', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_reading_sessions', to='books.book')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField()),
                ('position', models.JSONField(default=dict)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='books.book')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('user_id', 'book', 'page_number', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ScreenshotWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('last_warning', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('message', models.TextField(default='Screenshots are disabled to protect author copyright. Please respect intellectual property rights.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_warnings', to='books.book')),
            ],
            options={
                'unique_together': {('user_id', 'book')},
            },
        ),
    ]
