# Generated by Django 6.0.3 on 2026-03-22 16:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_content_source_book_is_free_book_manual_content_and_more'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_book_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pages', models.PositiveIntegerField()),
                ('per_page_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('charged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_charges', to='books.book')),
            ],
            options={
                'ordering': ['page_number'],
                'indexes': [models.Index(fields=['user_id', 'book'], name='reader_page_user_id_c7993d_idx'), models.Index(fields=['charged_at'], name='reader_page_charged_b65026_idx')],
                'unique_together': {('user_id', 'book', 'page_number')},
            },
        ),
    ]
