# Generated by Django 6.0.3 on 2026-03-25 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_content_source_book_is_free_book_manual_content_and_more'),
        ('reader', '0002_pagecharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField()),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_pages', to='books.book')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'indexes': [models.Index(fields=['user_id', 'book'], name='reader_unlo_user_id_2a1c27_idx'), models.Index(fields=['user_id', 'book', 'page_number'], name='reader_unlo_user_id_04c654_idx')],
                'unique_together': {('user_id', 'book', 'page_number')},
            },
        ),
    ]
